### ISSUE TITLE
WindowsAzure.Storage Version 9.1.0 did not work with Storage Emulator 5.2.0.

### ISSUE THREAD

**Issue by levilime** [Azure-Samples/storage-blob-dotnet-getting-started#9]
When running the project I got the following error with Storage Emulator 5.2.0.

```
"The REST version of this request is not supported by this release of the Storage Emulator. Please upgrade the storage emulator to the latest version. Refer to the following URL for more information: http://go.microsoft.com/fwlink/?LinkId=392237"
```
From this [source](https://stackoverflow.com/questions/46311458/the-rest-version-of-this-request-is-not-supported-by-this-release-of-the-storage) I downgraded to WindowsAzure.Storage Version 8.6.0 .

And this made it work.

**Comment by hodoje** [comment]
Had the same problem. Installed the standalone version of Storage Emulator 5.3.0 from https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator and it works now.
